import "./globals.css";
import { NextAuthProvider } from "./providers";
import {Instrument_Sans} from "next/font/google"
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const InstrumentSans = Instrument_Sans({subsets: ['latin']});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={InstrumentSans.className}>
      <body>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
